# vehicle_database.py
# Komplette Fahrzeugdatenbank - separat von main.py

VEHICLE_DATABASE = {
    # === VW ===
    "VW up!": {"category": "Kleinstwagen", "segment": "City-Car", "body_type": "Kleinwagen", "new_price": 13500, "hp": 75, "engine": 1.0},
    "VW Polo": {"category": "Kleinwagen", "segment": "Supermini", "body_type": "Kleinwagen", "new_price": 18000, "hp": 95, "engine": 1.0},
    "VW Golf": {"category": "Kompakt", "segment": "Kompaktklasse", "body_type": "Schrägheck", "new_price": 30000, "hp": 130, "engine": 1.5},
    "VW Golf GTI": {"category": "Sport", "segment": "Hot Hatch", "body_type": "Schrägheck", "new_price": 42000, "hp": 245, "engine": 2.0},
    "VW Golf R": {"category": "Sport", "segment": "Performance Hatch", "body_type": "Schrägheck", "new_price": 52000, "hp": 320, "engine": 2.0},
    "VW Passat": {"category": "Mittelklasse", "segment": "Mittelklasse Limousine", "body_type": "Limousine", "new_price": 42000, "hp": 190, "engine": 2.0},
    "VW Passat Variant": {"category": "Mittelklasse", "segment": "Mittelklasse Kombi", "body_type": "Kombi", "new_price": 44000, "hp": 190, "engine": 2.0},
    "VW Arteon": {"category": "Oberklasse", "segment": "Gran Turismo", "body_type": "Fastback", "new_price": 52000, "hp": 280, "engine": 2.0},
    "VW T-Roc": {"category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_type": "SUV", "new_price": 28000, "hp": 150, "engine": 1.5},
    "VW T-Roc Cabrio": {"category": "SUV-Cabrio", "segment": "Cabrio-SUV", "body_type": "Cabriolet", "new_price": 35000, "hp": 150, "engine": 1.5},
    "VW Tiguan": {"category": "SUV-Mittel", "segment": "Mittelklasse-SUV", "body_type": "SUV", "new_price": 38000, "hp": 190, "engine": 2.0},
    "VW Touareg": {"category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_type": "SUV", "new_price": 68000, "hp": 286, "engine": 3.0},
    "VW Caddy": {"category": "Hochdachkombi", "segment": "Kastenwagen", "body_type": "Van", "new_price": 27000, "hp": 122, "engine": 2.0},
    "VW T6": {"category": "Transporter", "segment": "Großraum-Van", "body_type": "Van", "new_price": 38000, "hp": 150, "engine": 2.0},
    
    # === BMW ===
    "BMW 1er": {"category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_type": "Schrägheck", "new_price": 34000, "hp": 140, "engine": 1.5},
    "BMW 2er": {"category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_type": "Coupé", "new_price": 38000, "hp": 170, "engine": 2.0},
    "BMW 2er Cabrio": {"category": "Cabrio-Premium", "segment": "Premium-Cabriolet", "body_type": "Cabriolet", "new_price": 42000, "hp": 184, "engine": 2.0},
    "BMW 3er": {"category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_type": "Limousine", "new_price": 48000, "hp": 184, "engine": 2.0},
    "BMW 3er Touring": {"category": "Mittelklasse-Premium", "segment": "Premium-Kombi", "body_type": "Kombi", "new_price": 51000, "hp": 184, "engine": 2.0},
    "BMW 4er": {"category": "Coupé-Premium", "segment": "Premium-Coupé", "body_type": "Coupé", "new_price": 52000, "hp": 258, "engine": 2.0},
    "BMW 4er Cabrio": {"category": "Cabrio-Premium", "segment": "Premium-Cabriolet", "body_type": "Cabriolet", "new_price": 60000, "hp": 258, "engine": 2.0},
    "BMW 5er": {"category": "Oberklasse", "segment": "Obere Mittelklasse", "body_type": "Limousine", "new_price": 72000, "hp": 292, "engine": 3.0},
    "BMW 5er Touring": {"category": "Oberklasse", "segment": "Premium-Kombi", "body_type": "Kombi", "new_price": 75000, "hp": 292, "engine": 3.0},
    "BMW 7er": {"category": "Luxus", "segment": "Oberklasse Limousine", "body_type": "Limousine", "new_price": 115000, "hp": 381, "engine": 3.0},
    "BMW 8er": {"category": "Luxus-Coupé", "segment": "Gran Turismo", "body_type": "Coupé", "new_price": 105000, "hp": 340, "engine": 3.0},
    "BMW 8er Cabrio": {"category": "Luxus-Cabrio", "segment": "Luxus-Cabriolet", "body_type": "Cabriolet", "new_price": 115000, "hp": 340, "engine": 3.0},
    "BMW X1": {"category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_type": "SUV", "new_price": 42000, "hp": 170, "engine": 2.0},
    "BMW X2": {"category": "SUV-Coupé", "segment": "SUV-Coupé", "body_type": "SUV", "new_price": 40000, "hp": 178, "engine": 2.0},
    "BMW X3": {"category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_type": "SUV", "new_price": 52000, "hp": 252, "engine": 2.0},
    "BMW X4": {"category": "SUV-Coupé", "segment": "Premium-SUV-Coupé", "body_type": "SUV", "new_price": 60000, "hp": 252, "engine": 2.0},
    "BMW X5": {"category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_type": "SUV", "new_price": 78000, "hp": 340, "engine": 3.0},
    "BMW X6": {"category": "SUV-Coupé", "segment": "SAC", "body_type": "SUV", "new_price": 85000, "hp": 340, "engine": 3.0},
    "BMW X7": {"category": "SUV-Luxus", "segment": "Luxus-SUV", "body_type": "SUV", "new_price": 98000, "hp": 340, "engine": 3.0},
    "BMW Z4": {"category": "Roadster", "segment": "Premium-Roadster", "body_type": "Roadster", "new_price": 55000, "hp": 197, "engine": 2.0},
    "BMW M2": {"category": "Sportwagen", "segment": "Performance-Coupé", "body_type": "Coupé", "new_price": 75000, "hp": 460, "engine": 3.0},
    "BMW M3": {"category": "Sportwagen", "segment": "Performance-Limousine", "body_type": "Limousine", "new_price": 88000, "hp": 510, "engine": 3.0},
    "BMW M4": {"category": "Sportwagen", "segment": "Performance-Coupé", "body_type": "Coupé", "new_price": 92000, "hp": 510, "engine": 3.0},
    "BMW M5": {"category": "Supersportwagen", "segment": "Performance-Limousine", "body_type": "Limousine", "new_price": 125000, "hp": 625, "engine": 4.4},
    "BMW i3": {"category": "Elektro-Kompakt", "segment": "Elektro-Kleinwagen", "body_type": "Schrägheck", "new_price": 38000, "hp": 170, "engine": 0.0},
    "BMW i4": {"category": "Elektro-Premium", "segment": "Elektro-Gran-Coupé", "body_type": "Limousine", "new_price": 60000, "hp": 340, "engine": 0.0},
    "BMW iX": {"category": "Elektro-SUV", "segment": "Elektro-Luxus-SUV", "body_type": "SUV", "new_price": 85000, "hp": 326, "engine": 0.0},
    
    # === MERCEDES ===
    "Mercedes A-Klasse": {"category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_type": "Schrägheck", "new_price": 35000, "hp": 163, "engine": 1.3},
    "Mercedes B-Klasse": {"category": "Kompakt-Van", "segment": "Premium-Kompakt-Van", "body_type": "Van", "new_price": 37000, "hp": 163, "engine": 1.3},
    "Mercedes C-Klasse": {"category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_type": "Limousine", "new_price": 52000, "hp": 204, "engine": 2.0},
    "Mercedes C-Klasse T-Modell": {"category": "Mittelklasse-Premium", "segment": "Premium-Kombi", "body_type": "Kombi", "new_price": 55000, "hp": 204, "engine": 2.0},
    "Mercedes C-Klasse Coupé": {"category": "Coupé-Premium", "segment": "Premium-Coupé", "body_type": "Coupé", "new_price": 50000, "hp": 204, "engine": 2.0},
    "Mercedes C-Klasse Cabrio": {"category": "Cabrio-Premium", "segment": "Premium-Cabriolet", "body_type": "Cabriolet", "new_price": 56000, "hp": 204, "engine": 2.0},
    "Mercedes E-Klasse": {"category": "Oberklasse", "segment": "Obere Mittelklasse", "body_type": "Limousine", "new_price": 70000, "hp": 272, "engine": 2.0},
    "Mercedes E-Klasse T-Modell": {"category": "Oberklasse", "segment": "Premium-Kombi", "body_type": "Kombi", "new_price": 74000, "hp": 272, "engine": 2.0},
    "Mercedes E-Klasse Coupé": {"category": "Luxus-Coupé", "segment": "Luxus-Coupé", "body_type": "Coupé", "new_price": 68000, "hp": 299, "engine": 2.0},
    "Mercedes E-Klasse Cabrio": {"category": "Luxus-Cabrio", "segment": "Luxus-Cabriolet", "body_type": "Cabriolet", "new_price": 74000, "hp": 299, "engine": 2.0},
    "Mercedes S-Klasse": {"category": "Luxus", "segment": "Luxus-Limousine", "body_type": "Limousine", "new_price": 120000, "hp": 435, "engine": 3.0},
    "Mercedes CLA": {"category": "Coupé-Premium", "segment": "Viertürer-Coupé", "body_type": "Coupé", "new_price": 38000, "hp": 163, "engine": 1.3},
    "Mercedes CLS": {"category": "Luxus-Coupé", "segment": "Viertürer-Coupé", "body_type": "Coupé", "new_price": 75000, "hp": 299, "engine": 2.0},
    "Mercedes GLA": {"category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_type": "SUV", "new_price": 40000, "hp": 163, "engine": 1.3},
    "Mercedes GLB": {"category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_type": "SUV", "new_price": 42000, "hp": 163, "engine": 1.3},
    "Mercedes GLC": {"category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_type": "SUV", "new_price": 58000, "hp": 258, "engine": 2.0},
    "Mercedes GLC Coupé": {"category": "SUV-Coupé", "segment": "SUV-Coupé", "body_type": "SUV", "new_price": 60000, "hp": 258, "engine": 2.0},
    "Mercedes GLE": {"category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_type": "SUV", "new_price": 75000, "hp": 367, "engine": 3.0},
    "Mercedes GLE Coupé": {"category": "SUV-Coupé", "segment": "Oberklasse-SUV-Coupé", "body_type": "SUV", "new_price": 82000, "hp": 367, "engine": 3.0},
    "Mercedes GLS": {"category": "SUV-Luxus", "segment": "Luxus-SUV", "body_type": "SUV", "new_price": 95000, "hp": 367, "engine": 3.0},
    "Mercedes G-Klasse": {"category": "SUV-Offroad", "segment": "Geländewagen", "body_type": "SUV", "new_price": 130000, "hp": 422, "engine": 4.0},
    "Mercedes SL": {"category": "Luxus-Roadster", "segment": "Luxus-Roadster", "body_type": "Roadster", "new_price": 145000, "hp": 476, "engine": 4.0},
    "Mercedes AMG GT": {"category": "Supersportwagen", "segment": "GT-Sportwagen", "body_type": "Coupé", "new_price": 145000, "hp": 585, "engine": 4.0},
    "Mercedes EQC": {"category": "Elektro-SUV", "segment": "Elektro-SUV", "body_type": "SUV", "new_price": 68000, "hp": 408, "engine": 0.0},
    "Mercedes EQS": {"category": "Elektro-Luxus", "segment": "Elektro-Luxuslimousine", "body_type": "Limousine", "new_price": 110000, "hp": 333, "engine": 0.0},
    "Mercedes Sprinter": {"category": "Transporter", "segment": "Kastenwagen", "body_type": "Van", "new_price": 42000, "hp": 143, "engine": 2.0},
    
    # === AUDI ===
    "Audi A1": {"category": "Kleinwagen", "segment": "Premium-Kleinwagen", "body_type": "Kleinwagen", "new_price": 26000, "hp": 116, "engine": 1.0},
    "Audi A3": {"category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_type": "Schrägheck", "new_price": 34000, "hp": 150, "engine": 1.5},
    "Audi A3 Limousine": {"category": "Kompakt-Premium", "segment": "Premium-Kompaktlimousine", "body_type": "Limousine", "new_price": 32000, "hp": 150, "engine": 1.5},
    "Audi A3 Cabrio": {"category": "Cabrio-Premium", "segment": "Premium-Cabriolet", "body_type": "Cabriolet", "new_price": 40000, "hp": 150, "engine": 1.4},
    "Audi A4": {"category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_type": "Limousine", "new_price": 42000, "hp": 150, "engine": 2.0},
    "Audi A4 Avant": {"category": "Mittelklasse-Premium", "segment": "Premium-Kombi", "body_type": "Kombi", "new_price": 45000, "hp": 150, "engine": 2.0},
    "Audi A5": {"category": "Coupé-Premium", "segment": "Premium-Coupé", "body_type": "Coupé", "new_price": 48000, "hp": 190, "engine": 2.0},
    "Audi A5 Cabrio": {"category": "Cabrio-Premium", "segment": "Premium-Cabriolet", "body_type": "Cabriolet", "new_price": 54000, "hp": 190, "engine": 2.0},
    "Audi A6": {"category": "Oberklasse", "segment": "Obere Mittelklasse", "body_type": "Limousine", "new_price": 58000, "hp": 204, "engine": 2.0},
    "Audi A6 Avant": {"category": "Oberklasse", "segment": "Premium-Kombi", "body_type": "Kombi", "new_price": 62000, "hp": 204, "engine": 2.0},
    "Audi A7": {"category": "Luxus-Coupé", "segment": "Sportback", "body_type": "Fastback", "new_price": 72000, "hp": 340, "engine": 3.0},
    "Audi A8": {"category": "Luxus", "segment": "Luxus-Limousine", "body_type": "Limousine", "new_price": 95000, "hp": 340, "engine": 3.0},
    "Audi Q2": {"category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_type": "SUV", "new_price": 28000, "hp": 116, "engine": 1.0},
    "Audi Q3": {"category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_type": "SUV", "new_price": 38000, "hp": 150, "engine": 1.5},
    "Audi Q5": {"category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_type": "SUV", "new_price": 52000, "hp": 204, "engine": 2.0},
    "Audi Q7": {"category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_type": "SUV", "new_price": 68000, "hp": 340, "engine": 3.0},
    "Audi Q8": {"category": "SUV-Luxus", "segment": "Luxus-SUV-Coupé", "body_type": "SUV", "new_price": 82000, "hp": 340, "engine": 3.0},
    "Audi TT": {"category": "Sportwagen", "segment": "Sport-Coupé", "body_type": "Coupé", "new_price": 42000, "hp": 230, "engine": 2.0},
    "Audi TT Roadster": {"category": "Roadster", "segment": "Sport-Roadster", "body_type": "Roadster", "new_price": 48000, "hp": 230, "engine": 2.0},
    "Audi R8": {"category": "Supersportwagen", "segment": "Supersportwagen", "body_type": "Coupé", "new_price": 175000, "hp": 570, "engine": 5.2},
    "Audi RS3": {"category": "Sportwagen", "segment": "Performance-Kompaktklasse", "body_type": "Limousine", "new_price": 62000, "hp": 400, "engine": 2.5},
    "Audi RS6 Avant": {"category": "Supersportwagen", "segment": "Performance-Kombi", "body_type": "Kombi", "new_price": 125000, "hp": 600, "engine": 4.0},
    "Audi e-tron": {"category": "Elektro-SUV", "segment": "Elektro-Premium-SUV", "body_type": "SUV", "new_price": 75000, "hp": 408, "engine": 0.0},
    "Audi e-tron GT": {"category": "Elektro-Sportwagen", "segment": "Elektro-Gran-Turismo", "body_type": "Limousine", "new_price": 105000, "hp": 530, "engine": 0.0},
    
    # === PORSCHE ===
    "Porsche 911": {"category": "Supersportwagen", "segment": "Ikonen-Sportwagen", "body_type": "Coupé", "new_price": 130000, "hp": 385, "engine": 3.0},
    "Porsche 911 Cabrio": {"category": "Supersportwagen", "segment": "Sportwagen-Cabriolet", "body_type": "Cabriolet", "new_price": 145000, "hp": 385, "engine": 3.0},
    "Porsche 911 Turbo": {"category": "Supersportwagen", "segment": "Turbo-Sportwagen", "body_type": "Coupé", "new_price": 210000, "hp": 580, "engine": 3.8},
    "Porsche 718 Cayman": {"category": "Sportwagen", "segment": "Mittelmotor-Sportwagen", "body_type": "Coupé", "new_price": 65000, "hp": 300, "engine": 2.0},
    "Porsche 718 Boxster": {"category": "Roadster", "segment": "Mittelmotor-Roadster", "body_type": "Roadster", "new_price": 68000, "hp": 300, "engine": 2.0},
    "Porsche Cayenne": {"category": "SUV-Premium", "segment": "Luxus-SUV", "body_type": "SUV", "new_price": 82000, "hp": 340, "engine": 3.0},
    "Porsche Macan": {"category": "SUV-Sport", "segment": "Sport-SUV", "body_type": "SUV", "new_price": 62000, "hp": 265, "engine": 2.0},
    "Porsche Panamera": {"category": "Luxus-Sportwagen", "segment": "Gran Turismo", "body_type": "Limousine", "new_price": 95000, "hp": 330, "engine": 2.9},
    "Porsche Taycan": {"category": "Elektro-Sportwagen", "segment": "Elektro-Gran-Turismo", "body_type": "Limousine", "new_price": 95000, "hp": 408, "engine": 0.0},
    
    # === TESLA ===
    "Tesla Model 3": {"category": "Elektro-Mittelklasse", "segment": "Elektro-Limousine", "body_type": "Limousine", "new_price": 48000, "hp": 325, "engine": 0.0},
    "Tesla Model S": {"category": "Elektro-Oberklasse", "segment": "Elektro-Luxuslimousine", "body_type": "Limousine", "new_price": 95000, "hp": 670, "engine": 0.0},
    "Tesla Model X": {"category": "Elektro-SUV", "segment": "Elektro-Luxus-SUV", "body_type": "SUV", "new_price": 105000, "hp": 670, "engine": 0.0},
    "Tesla Model Y": {"category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_type": "SUV", "new_price": 58000, "hp": 462, "engine": 0.0},
    
    # === FERRARI ===
    "Ferrari F8": {"category": "Supersportwagen", "segment": "Supersportwagen", "body_type": "Coupé", "new_price": 280000, "hp": 720, "engine": 3.9},
    "Ferrari Roma": {"category": "Supersportwagen", "segment": "Gran Turismo", "body_type": "Coupé", "new_price": 235000, "hp": 620, "engine": 3.9},
    "Ferrari Portofino": {"category": "Supersportwagen", "segment": "GT-Cabrio", "body_type": "Cabriolet", "new_price": 225000, "hp": 600, "engine": 3.9},
    
    # === LAMBORGHINI ===
    "Lamborghini Huracán": {"category": "Supersportwagen", "segment": "Supersportwagen", "body_type": "Coupé", "new_price": 220000, "hp": 640, "engine": 5.2},
    "Lamborghini Aventador": {"category": "Supersportwagen", "segment": "Flaggschiff-Supersportwagen", "body_type": "Coupé", "new_price": 380000, "hp": 770, "engine": 6.5},
    "Lamborghini Urus": {"category": "SUV-Super", "segment": "Super-SUV", "body_type": "SUV", "new_price": 220000, "hp": 650, "engine": 4.0},
    
    # === BENTLEY ===
    "Bentley Continental GT": {"category": "Luxus-Sportwagen", "segment": "Luxus-Gran-Turismo", "body_type": "Coupé", "new_price": 220000, "hp": 550, "engine": 4.0},
    "Bentley Flying Spur": {"category": "Ultraluxus", "segment": "Luxus-Limousine", "body_type": "Limousine", "new_price": 230000, "hp": 550, "engine": 4.0},
    "Bentley Bentayga": {"category": "SUV-Ultraluxus", "segment": "Luxus-SUV", "body_type": "SUV", "new_price": 200000, "hp": 550, "engine": 4.0},
    
    # === ROLLS-ROYCE ===
    "Rolls-Royce Ghost": {"category": "Ultraluxus", "segment": "Luxus-Limousine", "body_type": "Limousine", "new_price": 320000, "hp": 571, "engine": 6.75},
    "Rolls-Royce Phantom": {"category": "Ultraluxus", "segment": "Flaggschiff-Limousine", "body_type": "Limousine", "new_price": 450000, "hp": 571, "engine": 6.75},
    "Rolls-Royce Cullinan": {"category": "SUV-Ultraluxus", "segment": "Ultra-Luxus-SUV", "body_type": "SUV", "new_price": 350000, "hp": 571, "engine": 6.75},
    
    # === WEITERE MARKEN ===
    "Opel Corsa": {"category": "Kleinwagen", "segment": "Kleinwagen", "body_type": "Kleinwagen", "new_price": 18000, "hp": 100, "engine": 1.2},
    "Opel Astra": {"category": "Kompakt", "segment": "Kompaktklasse", "body_type": "Schrägheck", "new_price": 26000, "hp": 130, "engine": 1.2},
    "Opel Insignia": {"category": "Mittelklasse", "segment": "Mittelklasse", "body_type": "Limousine", "new_price": 32000, "hp": 165, "engine": 2.0},
    "Opel Mokka": {"category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_type": "SUV", "new_price": 25000, "hp": 130, "engine": 1.2},
    "Ford Fiesta": {"category": "Kleinwagen", "segment": "Kleinwagen", "body_type": "Kleinwagen", "new_price": 18000, "hp": 85, "engine": 1.1},
    "Ford Focus": {"category": "Kompakt", "segment": "Kompaktklasse", "body_type": "Schrägheck", "new_price": 26000, "hp": 125, "engine": 1.0},
    "Ford Mustang": {"category": "Sportwagen", "segment": "Muscle Car", "body_type": "Coupé", "new_price": 52000, "hp": 450, "engine": 5.0},
    "Ford Mustang Cabrio": {"category": "Cabrio-Sport", "segment": "Muscle Cabrio", "body_type": "Cabriolet", "new_price": 58000, "hp": 450, "engine": 5.0},
    "Ford Kuga": {"category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_type": "SUV", "new_price": 32000, "hp": 150, "engine": 1.5},
    "Fiat 500": {"category": "Kleinstwagen", "segment": "Retro-Kleinwagen", "body_type": "Kleinwagen", "new_price": 16000, "hp": 69, "engine": 1.2},
    "Fiat 500 Cabrio": {"category": "Cabrio-Klein", "segment": "City-Cabrio", "body_type": "Cabriolet", "new_price": 19000, "hp": 69, "engine": 1.2},
    "Fiat 500X": {"category": "SUV-Klein", "segment": "Mini-SUV", "body_type": "SUV", "new_price": 24000, "hp": 120, "engine": 1.0},
    "Renault Clio": {"category": "Kleinwagen", "segment": "Kleinwagen", "body_type": "Kleinwagen", "new_price": 18000, "hp": 90, "engine": 1.0},
    "Renault Megane": {"category": "Kompakt", "segment": "Kompaktklasse", "body_type": "Schrägheck", "new_price": 26000, "hp": 140, "engine": 1.3},
    "Renault Captur": {"category": "SUV-Klein", "segment": "Mini-SUV", "body_type": "SUV", "new_price": 24000, "hp": 130, "engine": 1.3},
    "Seat Ibiza": {"category": "Kleinwagen", "segment": "Kleinwagen", "body_type": "Kleinwagen", "new_price": 18000, "hp": 95, "engine": 1.0},
    "Seat Leon": {"category": "Kompakt", "segment": "Kompaktklasse", "body_type": "Schrägheck", "new_price": 26000, "hp": 110, "engine": 1.0},
    "Seat Ateca": {"category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_type": "SUV", "new_price": 28000, "hp": 110, "engine": 1.0},
    "Skoda Fabia": {"category": "Kleinwagen", "segment": "Kleinwagen", "body_type": "Kleinwagen", "new_price": 18000, "hp": 95, "engine": 1.0},
    "Skoda Octavia": {"category": "Kompakt", "segment": "Kompaktklasse", "body_type": "Limousine", "new_price": 28000, "hp": 150, "engine": 1.5},
    "Skoda Octavia Combi": {"category": "Kompakt", "segment": "Kompakt-Kombi", "body_type": "Kombi", "new_price": 30000, "hp": 150, "engine": 1.5},
    "Skoda Superb": {"category": "Mittelklasse", "segment": "Mittelklasse", "body_type": "Limousine", "new_price": 38000, "hp": 190, "engine": 2.0},
    "Skoda Kodiaq": {"category": "SUV-Mittel", "segment": "Mittelklasse-SUV", "body_type": "SUV", "new_price": 36000, "hp": 150, "engine": 1.5},
    "Mazda MX-5": {"category": "Roadster", "segment": "Roadster", "body_type": "Roadster", "new_price": 32000, "hp": 184, "engine": 2.0},
    "Mazda 3": {"category": "Kompakt", "segment": "Kompaktklasse", "body_type": "Schrägheck", "new_price": 26000, "hp": 122, "engine": 2.0},
    "Mazda CX-5": {"category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_type": "SUV", "new_price": 32000, "hp": 165, "engine": 2.0},
    "Mini Cooper": {"category": "Kleinwagen", "segment": "Premium-Kleinwagen", "body_type": "Kleinwagen", "new_price": 24000, "hp": 136, "engine": 1.5},
    "Mini Cooper Cabrio": {"category": "Cabrio-Klein", "segment": "Premium-City-Cabrio", "body_type": "Cabriolet", "new_price": 30000, "hp": 136, "engine": 1.5},
    "Mini Countryman": {"category": "SUV-Klein", "segment": "Premium-Mini-SUV", "body_type": "SUV", "new_price": 32000, "hp": 136, "engine": 1.5},
}

BASE_HOURLY_RATES = {
    "Kleinstwagen": 5.5,
    "Kleinwagen": 7.0,
    "Kompakt": 9.5,
    "Kompakt-Premium": 12.0,
    "Mittelklasse": 13.5,
    "Mittelklasse-Premium": 16.0,
    "Oberklasse": 22.0,
    "Luxus": 35.0,
    "Ultraluxus": 75.0,
    "Coupé-Premium": 18.0,
    "Luxus-Coupé": 32.0,
    "Cabrio-Klein": 10.0,
    "Cabrio-Premium": 20.0,
    "Luxus-Cabrio": 40.0,
    "Cabrio-Sport": 28.0,
    "Roadster": 22.0,
    "Luxus-Roadster": 45.0,
    "SUV-Klein": 10.0,
    "SUV-Kompakt": 12.0,
    "SUV-Mittel": 16.0,
    "SUV-Sport": 24.0,
    "SUV-Premium": 26.0,
    "SUV-Luxus": 38.0,
    "SUV-Ultraluxus": 65.0,
    "SUV-Super": 55.0,
    "SUV-Offroad": 28.0,
    "SUV-Coupé": 22.0,
    "SUV-Cabrio": 24.0,
    "Sport": 25.0,
    "Sportwagen": 38.0,
    "Luxus-Sportwagen": 55.0,
    "Supersportwagen": 85.0,
    "Transporter": 12.0,
    "Hochdachkombi": 10.0,
    "Kompakt-Van": 11.0,
    "Elektro-Kompakt": 11.0,
    "Elektro-Mittelklasse": 15.0,
    "Elektro-Premium": 20.0,
    "Elektro-Oberklasse": 28.0,
    "Elektro-Luxus": 40.0,
    "Elektro-SUV": 22.0,
    "Elektro-Sportwagen": 45.0,
}
