# vehicle_database.py
# Fahrzeugdatenbank - Liste von Fahrzeugen

VEHICLE_DATABASE = [
    # === VW ===
    {"brand": "VW", "model": "up!", "category": "Kleinstwagen", "segment": "City-Car", "body_style": "Kleinwagen", "new_price": 13500, "hp": 75, "engine_displacement": 1.0},
    {"brand": "VW", "model": "Polo", "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 18000, "hp": 95, "engine_displacement": 1.0},
    {"brand": "VW", "model": "Golf", "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 30000, "hp": 130, "engine_displacement": 1.5},
    {"brand": "VW", "model": "Golf GTI", "category": "Sport", "segment": "Hot Hatch", "body_style": "Schrägheck", "new_price": 42000, "hp": 245, "engine_displacement": 2.0},
    {"brand": "VW", "model": "Golf R", "category": "Sport", "segment": "Performance Hatch", "body_style": "Schrägheck", "new_price": 52000, "hp": 320, "engine_displacement": 2.0},
    {"brand": "VW", "model": "Passat", "category": "Mittelklasse", "segment": "Mittelklasse Limousine", "body_style": "Limousine", "new_price": 42000, "hp": 190, "engine_displacement": 2.0},
    {"brand": "VW", "model": "Passat Variant", "category": "Mittelklasse", "segment": "Mittelklasse Kombi", "body_style": "Kombi", "new_price": 44000, "hp": 190, "engine_displacement": 2.0},
    {"brand": "VW", "model": "Arteon", "category": "Oberklasse", "segment": "Gran Turismo", "body_style": "Fastback", "new_price": 52000, "hp": 280, "engine_displacement": 2.0},
    {"brand": "VW", "model": "T-Roc", "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 28000, "hp": 150, "engine_displacement": 1.5},
    {"brand": "VW", "model": "T-Roc Cabrio", "category": "SUV-Cabrio", "segment": "Cabrio-SUV", "body_style": "Cabrio", "new_price": 35000, "hp": 150, "engine_displacement": 1.5},
    {"brand": "VW", "model": "Tiguan", "category": "SUV-Mittel", "segment": "Mittelklasse-SUV", "body_style": "SUV", "new_price": 38000, "hp": 190, "engine_displacement": 2.0},
    {"brand": "VW", "model": "Touareg", "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 68000, "hp": 286, "engine_displacement": 3.0},
    {"brand": "VW", "model": "Caddy", "category": "Hochdachkombi", "segment": "Kastenwagen", "body_style": "Van", "new_price": 27000, "hp": 122, "engine_displacement": 2.0},
    {"brand": "VW", "model": "T6", "category": "Transporter", "segment": "Großraum-Van", "body_style": "Van", "new_price": 38000, "hp": 150, "engine_displacement": 2.0},
    
    # === BMW ===
    {"brand": "BMW", "model": "1er", "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Schrägheck", "new_price": 34000, "hp": 140, "engine_displacement": 1.5},
    {"brand": "BMW", "model": "2er", "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Coupé", "new_price": 38000, "hp": 170, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "2er Cabrio", "category": "Cabrio-Premium", "segment": "Premium-Cabriolet", "body_style": "Cabrio", "new_price": 42000, "hp": 184, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "3er", "category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 48000, "hp": 184, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "3er Touring", "category": "Mittelklasse-Premium", "segment": "Premium-Kombi", "body_style": "Kombi", "new_price": 51000, "hp": 184, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "4er", "category": "Coupé-Premium", "segment": "Premium-Coupé", "body_style": "Coupé", "new_price": 52000, "hp": 258, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "4er Cabrio", "category": "Cabrio-Premium", "segment": "Premium-Cabriolet", "body_style": "Cabrio", "new_price": 60000, "hp": 258, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "5er", "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 72000, "hp": 292, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "5er Touring", "category": "Oberklasse", "segment": "Premium-Kombi", "body_style": "Kombi", "new_price": 75000, "hp": 292, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "7er", "category": "Luxuslimousine", "segment": "Oberklasse Limousine", "body_style": "Limousine", "new_price": 115000, "hp": 381, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "8er", "category": "Luxus-Coupé", "segment": "Gran Turismo", "body_style": "Coupé", "new_price": 105000, "hp": 340, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "8er Cabrio", "category": "Luxus-Cabrio", "segment": "Luxus-Cabriolet", "body_style": "Cabrio", "new_price": 115000, "hp": 340, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "X1", "category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_style": "SUV", "new_price": 42000, "hp": 170, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "X2", "category": "SUV-Coupé", "segment": "SUV-Coupé", "body_style": "SUV", "new_price": 40000, "hp": 178, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "X3", "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 52000, "hp": 252, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "X4", "category": "SUV-Coupé", "segment": "Premium-SUV-Coupé", "body_style": "SUV", "new_price": 60000, "hp": 252, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "X5", "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 78000, "hp": 340, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "X6", "category": "SUV-Coupé", "segment": "SAC", "body_style": "SUV", "new_price": 85000, "hp": 340, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "X7", "category": "SUV-Luxus", "segment": "Luxus-SUV", "body_style": "SUV", "new_price": 98000, "hp": 340, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "Z4", "category": "Roadster", "segment": "Premium-Roadster", "body_style": "Roadster", "new_price": 55000, "hp": 197, "engine_displacement": 2.0},
    {"brand": "BMW", "model": "M2", "category": "Sportwagen", "segment": "Performance-Coupé", "body_style": "Coupé", "new_price": 75000, "hp": 460, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "M3", "category": "Sportwagen", "segment": "Performance-Limousine", "body_style": "Limousine", "new_price": 88000, "hp": 510, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "M4", "category": "Sportwagen", "segment": "Performance-Coupé", "body_style": "Coupé", "new_price": 92000, "hp": 510, "engine_displacement": 3.0},
    {"brand": "BMW", "model": "M5", "category": "Supersportwagen", "segment": "Performance-Limousine", "body_style": "Limousine", "new_price": 125000, "hp": 625, "engine_displacement": 4.4},
    {"brand": "BMW", "model": "i3", "category": "Elektro-Kompakt", "segment": "Elektro-Kleinwagen", "body_style": "Schrägheck", "new_price": 38000, "hp": 170, "engine_displacement": 0.0},
    {"brand": "BMW", "model": "i4", "category": "Elektro-Premium", "segment": "Elektro-Gran-Coupé", "body_style": "Limousine", "new_price": 60000, "hp": 340, "engine_displacement": 0.0},
    {"brand": "BMW", "model": "iX", "category": "Elektro-SUV", "segment": "Elektro-Luxus-SUV", "body_style": "SUV", "new_price": 85000, "hp": 326, "engine_displacement": 0.0},
    
    # === MERCEDES ===
    {"brand": "Mercedes", "model": "A-Klasse", "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Schrägheck", "new_price": 35000, "hp": 163, "engine_displacement": 1.3},
    {"brand": "Mercedes", "model": "B-Klasse", "category": "Kompakt-Van", "segment": "Premium-Kompakt-Van", "body_style": "Van", "new_price": 37000, "hp": 163, "engine_displacement": 1.3},
    {"brand": "Mercedes", "model": "C-Klasse", "category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 52000, "hp": 204, "engine_displacement": 2.0},
    {"brand": "Mercedes", "model": "E-Klasse", "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 70000, "hp": 272, "engine_displacement": 2.0},
    {"brand": "Mercedes", "model": "S-Klasse", "category": "Luxuslimousine", "segment": "Luxus-Limousine", "body_style": "Limousine", "new_price": 120000, "hp": 435, "engine_displacement": 3.0},
    {"brand": "Mercedes", "model": "GLA", "category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_style": "SUV", "new_price": 40000, "hp": 163, "engine_displacement": 1.3},
    {"brand": "Mercedes", "model": "GLC", "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 58000, "hp": 258, "engine_displacement": 2.0},
    {"brand": "Mercedes", "model": "GLE", "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 75000, "hp": 367, "engine_displacement": 3.0},
    {"brand": "Mercedes", "model": "G-Klasse", "category": "SUV-Offroad", "segment": "Geländewagen", "body_style": "SUV", "new_price": 130000, "hp": 422, "engine_displacement": 4.0},
    {"brand": "Mercedes", "model": "AMG GT", "category": "Supersportwagen", "segment": "GT-Sportwagen", "body_style": "Coupé", "new_price": 145000, "hp": 585, "engine_displacement": 4.0},
    
    # === AUDI ===
    {"brand": "Audi", "model": "A1", "category": "Kleinwagen", "segment": "Premium-Kleinwagen", "body_style": "Kleinwagen", "new_price": 26000, "hp": 116, "engine_displacement": 1.0},
    {"brand": "Audi", "model": "A3", "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Schrägheck", "new_price": 34000, "hp": 150, "engine_displacement": 1.5},
    {"brand": "Audi", "model": "A4", "category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 42000, "hp": 150, "engine_displacement": 2.0},
    {"brand": "Audi", "model": "A6", "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 58000, "hp": 204, "engine_displacement": 2.0},
    {"brand": "Audi", "model": "A8", "category": "Luxuslimousine", "segment": "Luxus-Limousine", "body_style": "Limousine", "new_price": 95000, "hp": 340, "engine_displacement": 3.0},
    {"brand": "Audi", "model": "Q3", "category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_style": "SUV", "new_price": 38000, "hp": 150, "engine_displacement": 1.5},
    {"brand": "Audi", "model": "Q5", "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 52000, "hp": 204, "engine_displacement": 2.0},
    {"brand": "Audi", "model": "Q7", "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 68000, "hp": 340, "engine_displacement": 3.0},
    {"brand": "Audi", "model": "TT", "category": "Sportwagen", "segment": "Sport-Coupé", "body_style": "Coupé", "new_price": 42000, "hp": 230, "engine_displacement": 2.0},
    {"brand": "Audi", "model": "R8", "category": "Supersportwagen", "segment": "Supersportwagen", "body_style": "Coupé", "new_price": 175000, "hp": 570, "engine_displacement": 5.2},
    
    # === PORSCHE ===
    {"brand": "Porsche", "model": "911", "category": "Supersportwagen", "segment": "Ikonen-Sportwagen", "body_style": "Coupé", "new_price": 130000, "hp": 385, "engine_displacement": 3.0},
    {"brand": "Porsche", "model": "718 Cayman", "category": "Sportwagen", "segment": "Mittelmotor-Sportwagen", "body_style": "Coupé", "new_price": 65000, "hp": 300, "engine_displacement": 2.0},
    {"brand": "Porsche", "model": "Cayenne", "category": "SUV-Premium", "segment": "Luxus-SUV", "body_style": "SUV", "new_price": 82000, "hp": 340, "engine_displacement": 3.0},
    {"brand": "Porsche", "model": "Macan", "category": "SUV-Sport", "segment": "Sport-SUV", "body_style": "SUV", "new_price": 62000, "hp": 265, "engine_displacement": 2.0},
    {"brand": "Porsche", "model": "Taycan", "category": "Elektro-Sportwagen", "segment": "Elektro-Gran-Turismo", "body_style": "Limousine", "new_price": 95000, "hp": 408, "engine_displacement": 0.0},
    
    # === TESLA ===
    {"brand": "Tesla", "model": "Model 3", "category": "Elektro-Mittelklasse", "segment": "Elektro-Limousine", "body_style": "Limousine", "new_price": 48000, "hp": 325, "engine_displacement": 0.0},
    {"brand": "Tesla", "model": "Model S", "category": "Elektro-Oberklasse", "segment": "Elektro-Luxuslimousine", "body_style": "Limousine", "new_price": 95000, "hp": 670, "engine_displacement": 0.0},
    {"brand": "Tesla", "model": "Model X", "category": "Elektro-SUV", "segment": "Elektro-Luxus-SUV", "body_style": "SUV", "new_price": 105000, "hp": 670, "engine_displacement": 0.0},
    {"brand": "Tesla", "model": "Model Y", "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 58000, "hp": 462, "engine_displacement": 0.0},
    
    # === FERRARI ===
    {"brand": "Ferrari", "model": "F8", "category": "Supersportwagen", "segment": "Supersportwagen", "body_style": "Coupé", "new_price": 280000, "hp": 720, "engine_displacement": 3.9},
    {"brand": "Ferrari", "model": "Roma", "category": "Supersportwagen", "segment": "Gran Turismo", "body_style": "Coupé", "new_price": 235000, "hp": 620, "engine_displacement": 3.9},
    
    # === LAMBORGHINI ===
    {"brand": "Lamborghini", "model": "Huracán", "category": "Supersportwagen", "segment": "Supersportwagen", "body_style": "Coupé", "new_price": 220000, "hp": 640, "engine_displacement": 5.2},
    {"brand": "Lamborghini", "model": "Urus", "category": "SUV-Super", "segment": "Super-SUV", "body_style": "SUV", "new_price": 220000, "hp": 650, "engine_displacement": 4.0},
    
    # === WEITERE ===
    {"brand": "Opel", "model": "Corsa", "category": "Kleinwagen", "segment": "Kleinwagen", "body_style": "Kleinwagen", "new_price": 18000, "hp": 100, "engine_displacement": 1.2},
    {"brand": "Ford", "model": "Fiesta", "category": "Kleinwagen", "segment": "Kleinwagen", "body_style": "Kleinwagen", "new_price": 18000, "hp": 85, "engine_displacement": 1.1},
    {"brand": "Ford", "model": "Mustang", "category": "Sportwagen", "segment": "Muscle Car", "body_style": "Coupé", "new_price": 52000, "hp": 450, "engine_displacement": 5.0},
    {"brand": "Fiat", "model": "500", "category": "Kleinstwagen", "segment": "Retro-Kleinwagen", "body_style": "Kleinwagen", "new_price": 16000, "hp": 69, "engine_displacement": 1.2},
    {"brand": "Renault", "model": "Clio", "category": "Kleinwagen", "segment": "Kleinwagen", "body_style": "Kleinwagen", "new_price": 18000, "hp": 90, "engine_displacement": 1.0},
    {"brand": "Seat", "model": "Ibiza", "category": "Kleinwagen", "segment": "Kleinwagen", "body_style": "Kleinwagen", "new_price": 18000, "hp": 95, "engine_displacement": 1.0},
    {"brand": "Skoda", "model": "Octavia", "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Limousine", "new_price": 28000, "hp": 150, "engine_displacement": 1.5},
    {"brand": "Mazda", "model": "MX-5", "category": "Roadster", "segment": "Roadster", "body_style": "Roadster", "new_price": 32000, "hp": 184, "engine_displacement": 2.0},
    {"brand": "Mini", "model": "Cooper", "category": "Kleinwagen", "segment": "Premium-Kleinwagen", "body_style": "Kleinwagen", "new_price": 24000, "hp": 136, "engine_displacement": 1.5},
]

BASE_HOURLY_RATES = {
    "Kleinstwagen": 5.5,
    "Kleinwagen": 7.0,
    "Kompakt": 9.5,
    "Kompakt-Premium": 12.0,
    "Mittelklasse": 13.5,
    "Mittelklasse-Premium": 16.0,
    "Oberklasse": 22.0,
    "Luxuslimousine": 35.0,
    "Ultraluxus": 75.0,
    "Coupé-Premium": 18.0,
    "Luxus-Coupé": 32.0,
    "Cabrio-Klein": 10.0,
    "Cabrio-Premium": 20.0,
    "Luxus-Cabrio": 40.0,
    "Cabrio-Sport": 28.0,
    "Roadster": 22.0,
    "Luxus-Roadster": 45.0,
    "SUV-Klein": 10.0,
    "SUV-Kompakt": 12.0,
    "SUV-Mittel": 16.0,
    "SUV-Sport": 24.0,
    "SUV-Premium": 26.0,
    "SUV-Luxus": 38.0,
    "SUV-Ultraluxus": 65.0,
    "SUV-Super": 55.0,
    "SUV-Offroad": 28.0,
    "SUV-Coupé": 22.0,
    "SUV-Cabrio": 24.0,
    "Sport": 25.0,
    "Sportwagen": 38.0,
    "Luxus-Sportwagen": 55.0,
    "Supersportwagen": 85.0,
    "Transporter": 12.0,
    "Hochdachkombi": 10.0,
    "Kompakt-Van": 11.0,
    "Elektro-Kompakt": 11.0,
    "Elektro-Mittelklasse": 15.0,
    "Elektro-Premium": 20.0,
    "Elektro-Oberklasse": 28.0,
    "Elektro-Luxus": 40.0,
    "Elektro-SUV": 22.0,
    "Elektro-Sportwagen": 45.0,
}
