# vehicle_database.py
# PROFI-FAHRZEUGDATENBANK - Optimiert für Free-Tier Deployment
# 300+ Fahrzeuge mit Generationen, Facelifts, Baujahren, Custom-Multipliers

VEHICLE_DATABASE = [
    # ========================================
    # VW - VOLKSWAGEN (20 Modelle)
    # ========================================
    {"brand": "VW", "model": "up!", "generation": "AA", "facelift": False, "year_start": 2011, "year_end": 2025, "category": "Kleinstwagen", "segment": "City-Car", "body_style": "Kleinwagen", "new_price": 13500, "hp": 75, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "Polo", "generation": "VI", "facelift": False, "year_start": 2017, "year_end": 2021, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 18000, "hp": 95, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "Polo", "generation": "VI FL", "facelift": True, "year_start": 2021, "year_end": 2025, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 20500, "hp": 95, "engine_displacement": 1.0, "rarity_multiplier": 1.0, "demand_factor": 1.05},
    {"brand": "VW", "model": "Golf", "generation": "VII", "facelift": False, "year_start": 2012, "year_end": 2017, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 25000, "hp": 110, "engine_displacement": 1.4, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "Golf", "generation": "VII FL", "facelift": True, "year_start": 2017, "year_end": 2019, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 27000, "hp": 130, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "Golf", "generation": "VIII", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 30000, "hp": 130, "engine_displacement": 1.5, "rarity_multiplier": 1.0, "demand_factor": 1.1},
    {"brand": "VW", "model": "Golf GTI", "generation": "VII", "facelift": False, "year_start": 2013, "year_end": 2017, "category": "Sport", "segment": "Hot Hatch", "body_style": "Schrägheck", "new_price": 35000, "hp": 220, "engine_displacement": 2.0, "special_edition": True, "rarity_multiplier": 1.15},
    {"brand": "VW", "model": "Golf GTI", "generation": "VIII", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Sport", "segment": "Hot Hatch", "body_style": "Schrägheck", "new_price": 42000, "hp": 245, "engine_displacement": 2.0, "special_edition": True, "rarity_multiplier": 1.2, "demand_factor": 1.15},
    {"brand": "VW", "model": "Golf R", "generation": "VII", "facelift": False, "year_start": 2014, "year_end": 2019, "category": "Sport", "segment": "Performance Hatch", "body_style": "Schrägheck", "new_price": 45000, "hp": 300, "engine_displacement": 2.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.25},
    {"brand": "VW", "model": "Golf R", "generation": "VIII", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Sport", "segment": "Performance Hatch", "body_style": "Schrägheck", "new_price": 52000, "hp": 320, "engine_displacement": 2.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.3, "demand_factor": 1.2},
    {"brand": "VW", "model": "Passat", "generation": "B8", "facelift": False, "year_start": 2014, "year_end": 2019, "category": "Mittelklasse", "segment": "Mittelklasse Limousine", "body_style": "Limousine", "new_price": 38000, "hp": 150, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "Passat", "generation": "B8 FL", "facelift": True, "year_start": 2019, "year_end": 2022, "category": "Mittelklasse", "segment": "Mittelklasse Limousine", "body_style": "Limousine", "new_price": 42000, "hp": 190, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "T-Roc", "generation": "A1", "facelift": False, "year_start": 2017, "year_end": 2022, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 26000, "hp": 110, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "T-Roc", "generation": "A1 FL", "facelift": True, "year_start": 2022, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 28000, "hp": 150, "engine_displacement": 1.5, "rarity_multiplier": 1.0, "demand_factor": 1.08},
    {"brand": "VW", "model": "Tiguan", "generation": "II", "facelift": False, "year_start": 2016, "year_end": 2020, "category": "SUV-Mittel", "segment": "Mittelklasse-SUV", "body_style": "SUV", "new_price": 35000, "hp": 150, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "Tiguan", "generation": "II FL", "facelift": True, "year_start": 2020, "year_end": 2025, "category": "SUV-Mittel", "segment": "Mittelklasse-SUV", "body_style": "SUV", "new_price": 38000, "hp": 190, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "VW", "model": "Touareg", "generation": "III", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 65000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.1},
    {"brand": "VW", "model": "Arteon", "generation": "I", "facelift": False, "year_start": 2017, "year_end": 2020, "category": "Mittelklasse-Premium", "segment": "Gran Turismo", "body_style": "Limousine", "new_price": 45000, "hp": 190, "engine_displacement": 2.0, "rarity_multiplier": 1.05},
    {"brand": "VW", "model": "ID.3", "generation": "E1", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Elektro-Kompakt", "segment": "Elektro-Kompaktklasse", "body_style": "Schrägheck", "new_price": 38000, "hp": 204, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},
    {"brand": "VW", "model": "ID.4", "generation": "E2", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 46000, "hp": 204, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},

    # ========================================
    # BMW (30 Modelle)
    # ========================================
    {"brand": "BMW", "model": "1er", "generation": "F40", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Schrägheck", "new_price": 34000, "hp": 140, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "2er", "generation": "F44", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Limousine", "new_price": 36000, "hp": 140, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "3er", "generation": "G20", "facelift": False, "year_start": 2019, "year_end": 2022, "category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 45000, "hp": 184, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "3er", "generation": "G20 FL", "facelift": True, "year_start": 2022, "year_end": 2025, "category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 48000, "hp": 184, "engine_displacement": 2.0, "rarity_multiplier": 1.0, "demand_factor": 1.05},
    {"brand": "BMW", "model": "3er Touring", "generation": "G21", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Mittelklasse-Premium", "segment": "Premium-Kombi", "body_style": "Kombi", "new_price": 47000, "hp": 184, "engine_displacement": 2.0, "rarity_multiplier": 1.05},
    {"brand": "BMW", "model": "4er", "generation": "G22", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Coupé-Premium", "segment": "Premium-Coupé", "body_style": "Coupé", "new_price": 50000, "hp": 184, "engine_displacement": 2.0, "rarity_multiplier": 1.1},
    {"brand": "BMW", "model": "5er", "generation": "G30", "facelift": False, "year_start": 2017, "year_end": 2020, "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 65000, "hp": 252, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "5er", "generation": "G30 FL", "facelift": True, "year_start": 2020, "year_end": 2023, "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 72000, "hp": 292, "engine_displacement": 3.0, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "5er", "generation": "G60", "facelift": False, "year_start": 2023, "year_end": 2025, "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 78000, "hp": 292, "engine_displacement": 3.0, "rarity_multiplier": 1.05, "demand_factor": 1.15},
    {"brand": "BMW", "model": "7er", "generation": "G70", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Luxuslimousine", "segment": "Luxus-Limousine", "body_style": "Limousine", "new_price": 110000, "hp": 380, "engine_displacement": 3.0, "rarity_multiplier": 1.15, "demand_factor": 1.2},
    {"brand": "BMW", "model": "X1", "generation": "U11", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_style": "SUV", "new_price": 42000, "hp": 150, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "X3", "generation": "G01", "facelift": False, "year_start": 2017, "year_end": 2021, "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 48000, "hp": 184, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "X3", "generation": "G01 FL", "facelift": True, "year_start": 2021, "year_end": 2025, "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 52000, "hp": 252, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "X5", "generation": "G05", "facelift": False, "year_start": 2018, "year_end": 2023, "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 75000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.0},
    {"brand": "BMW", "model": "X5", "generation": "G05 FL", "facelift": True, "year_start": 2023, "year_end": 2025, "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 78000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.0, "demand_factor": 1.08},
    {"brand": "BMW", "model": "X7", "generation": "G07", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Luxus", "segment": "Luxus-SUV", "body_style": "SUV", "new_price": 95000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.1},
    {"brand": "BMW", "model": "M2", "generation": "G87", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Sportwagen", "segment": "Performance-Coupé", "body_style": "Coupé", "new_price": 75000, "hp": 460, "engine_displacement": 3.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.35, "demand_factor": 1.25},
    {"brand": "BMW", "model": "M3", "generation": "G80", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Sportwagen", "segment": "Performance-Limousine", "body_style": "Limousine", "new_price": 88000, "hp": 510, "engine_displacement": 3.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.4, "demand_factor": 1.3},
    {"brand": "BMW", "model": "M3 Competition", "generation": "G80", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Sportwagen", "segment": "Performance-Limousine", "body_style": "Limousine", "new_price": 95000, "hp": 510, "engine_displacement": 3.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.4},
    {"brand": "BMW", "model": "M4", "generation": "G82", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Sportwagen", "segment": "Performance-Coupé", "body_style": "Coupé", "new_price": 92000, "hp": 510, "engine_displacement": 3.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.4, "demand_factor": 1.35},
    {"brand": "BMW", "model": "M5", "generation": "F90", "facelift": False, "year_start": 2018, "year_end": 2023, "category": "Supersportwagen", "segment": "Performance-Limousine", "body_style": "Limousine", "new_price": 125000, "hp": 625, "engine_displacement": 4.4, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.4},
    {"brand": "BMW", "model": "M8", "generation": "F92", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Supersportwagen", "segment": "Gran Coupé Performance", "body_style": "Coupé", "new_price": 145000, "hp": 625, "engine_displacement": 4.4, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.6, "demand_factor": 1.5},
    {"brand": "BMW", "model": "i4", "generation": "G26", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-Premium", "segment": "Elektro-Gran-Coupé", "body_style": "Limousine", "new_price": 60000, "hp": 340, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},
    {"brand": "BMW", "model": "iX", "generation": "I20", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Luxus-SUV", "body_style": "SUV", "new_price": 85000, "hp": 326, "engine_displacement": 0.0, "rarity_multiplier": 1.15, "demand_factor": 1.2},
    {"brand": "BMW", "model": "iX3", "generation": "G08", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Mittelklasse-SUV", "body_style": "SUV", "new_price": 68000, "hp": 286, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},
    {"brand": "BMW", "model": "i7", "generation": "G70", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Elektro-Luxus", "segment": "Elektro-Luxuslimousine", "body_style": "Limousine", "new_price": 135000, "hp": 544, "engine_displacement": 0.0, "rarity_multiplier": 1.25, "demand_factor": 1.3},
    {"brand": "BMW", "model": "Z4", "generation": "G29", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Roadster", "segment": "Premium-Roadster", "body_style": "Roadster", "new_price": 58000, "hp": 258, "engine_displacement": 2.0, "rarity_multiplier": 1.2, "demand_factor": 1.15},
    {"brand": "BMW", "model": "8er", "generation": "G15", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Luxus-Coupé", "segment": "Gran Turismo", "body_style": "Coupé", "new_price": 105000, "hp": 530, "engine_displacement": 4.4, "rarity_multiplier": 1.3, "demand_factor": 1.25},
    {"brand": "BMW", "model": "iX1", "generation": "U11", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 48000, "hp": 313, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},
    {"brand": "BMW", "model": "XM", "generation": "G09", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "SUV-Super", "segment": "Performance-Hybrid-SUV", "body_style": "SUV", "new_price": 180000, "hp": 653, "engine_displacement": 4.4, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.7, "demand_factor": 1.6},

    # ========================================
    # MERCEDES-BENZ (30 Modelle)
    # ========================================
    {"brand": "Mercedes", "model": "A-Klasse", "generation": "W177", "facelift": False, "year_start": 2018, "year_end": 2022, "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Schrägheck", "new_price": 33000, "hp": 163, "engine_displacement": 1.3, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "A-Klasse", "generation": "W177 FL", "facelift": True, "year_start": 2022, "year_end": 2025, "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Schrägheck", "new_price": 35000, "hp": 163, "engine_displacement": 1.3, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "B-Klasse", "generation": "W247", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kompakt-Van", "segment": "Kompakt-Van", "body_style": "Van", "new_price": 38000, "hp": 163, "engine_displacement": 1.3, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "C-Klasse", "generation": "W206", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 52000, "hp": 204, "engine_displacement": 2.0, "rarity_multiplier": 1.05, "demand_factor": 1.1},
    {"brand": "Mercedes", "model": "C-Klasse T-Modell", "generation": "S206", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Mittelklasse-Premium", "segment": "Premium-Kombi", "body_style": "Kombi", "new_price": 54000, "hp": 204, "engine_displacement": 2.0, "rarity_multiplier": 1.05},
    {"brand": "Mercedes", "model": "E-Klasse", "generation": "W213", "facelift": False, "year_start": 2016, "year_end": 2020, "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 62000, "hp": 194, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "E-Klasse", "generation": "W213 FL", "facelift": True, "year_start": 2020, "year_end": 2023, "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 70000, "hp": 272, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "E-Klasse", "generation": "W214", "facelift": False, "year_start": 2023, "year_end": 2025, "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 72000, "hp": 272, "engine_displacement": 2.0, "rarity_multiplier": 1.05, "demand_factor": 1.1},
    {"brand": "Mercedes", "model": "S-Klasse", "generation": "W223", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Luxuslimousine", "segment": "Luxus-Limousine", "body_style": "Limousine", "new_price": 120000, "hp": 435, "engine_displacement": 3.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},
    {"brand": "Mercedes", "model": "CLA", "generation": "C118", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kompakt-Premium", "segment": "Kompakt-Coupé", "body_style": "Coupé", "new_price": 38000, "hp": 163, "engine_displacement": 1.3, "rarity_multiplier": 1.05},
    {"brand": "Mercedes", "model": "CLS", "generation": "C257", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Oberklasse", "segment": "Gran Coupé", "body_style": "Coupé", "new_price": 78000, "hp": 299, "engine_displacement": 3.0, "rarity_multiplier": 1.15},
    {"brand": "Mercedes", "model": "GLA", "generation": "H247", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_style": "SUV", "new_price": 40000, "hp": 163, "engine_displacement": 1.3, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "GLB", "generation": "X247", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV-7-Sitzer", "body_style": "SUV", "new_price": 44000, "hp": 163, "engine_displacement": 1.3, "rarity_multiplier": 1.05},
    {"brand": "Mercedes", "model": "GLC", "generation": "X253", "facelift": False, "year_start": 2015, "year_end": 2019, "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 52000, "hp": 211, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "GLC", "generation": "X253 FL", "facelift": True, "year_start": 2019, "year_end": 2022, "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 56000, "hp": 258, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "GLC", "generation": "X254", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 58000, "hp": 258, "engine_displacement": 2.0, "rarity_multiplier": 1.05, "demand_factor": 1.1},
    {"brand": "Mercedes", "model": "GLE", "generation": "W167", "facelift": False, "year_start": 2019, "year_end": 2023, "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 72000, "hp": 367, "engine_displacement": 3.0, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "GLE", "generation": "W167 FL", "facelift": True, "year_start": 2023, "year_end": 2025, "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 75000, "hp": 367, "engine_displacement": 3.0, "rarity_multiplier": 1.0},
    {"brand": "Mercedes", "model": "GLS", "generation": "X167", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Luxus", "segment": "Luxus-SUV", "body_style": "SUV", "new_price": 95000, "hp": 367, "engine_displacement": 3.0, "rarity_multiplier": 1.1},
    {"brand": "Mercedes", "model": "G-Klasse", "generation": "W463", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "SUV-Offroad", "segment": "Geländewagen", "body_style": "SUV", "new_price": 130000, "hp": 422, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.45, "demand_factor": 1.5},
    {"brand": "Mercedes", "model": "AMG A 45 S", "generation": "W177", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Sportwagen", "segment": "Performance-Kompaktklasse", "body_style": "Schrägheck", "new_price": 58000, "hp": 421, "engine_displacement": 2.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.35, "demand_factor": 1.3},
    {"brand": "Mercedes", "model": "AMG C 63", "generation": "W206", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Sportwagen", "segment": "Performance-Limousine", "body_style": "Limousine", "new_price": 95000, "hp": 510, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.4, "demand_factor": 1.35},
    {"brand": "Mercedes", "model": "AMG GT", "generation": "C190", "facelift": False, "year_start": 2014, "year_end": 2022, "category": "Supersportwagen", "segment": "GT-Sportwagen", "body_style": "Coupé", "new_price": 145000, "hp": 585, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.45},
    {"brand": "Mercedes", "model": "AMG GT", "generation": "C192", "facelift": False, "year_start": 2024, "year_end": 2025, "category": "Supersportwagen", "segment": "GT-Sportwagen", "body_style": "Coupé", "new_price": 160000, "hp": 585, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.55, "demand_factor": 1.5},
    {"brand": "Mercedes", "model": "EQA", "generation": "H243", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 48000, "hp": 190, "engine_displacement": 0.0, "rarity_multiplier": 1.05, "demand_factor": 1.1},
    {"brand": "Mercedes", "model": "EQB", "generation": "X243", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV-7-Sitzer", "body_style": "SUV", "new_price": 52000, "hp": 292, "engine_displacement": 0.0, "rarity_multiplier": 1.05, "demand_factor": 1.1},
    {"brand": "Mercedes", "model": "EQC", "generation": "N293", "facelift": False, "year_start": 2019, "year_end": 2023, "category": "Elektro-SUV", "segment": "Elektro-Mittelklasse-SUV", "body_style": "SUV", "new_price": 68000, "hp": 408, "engine_displacement": 0.0, "rarity_multiplier": 1.1},
    {"brand": "Mercedes", "model": "EQE", "generation": "V295", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Elektro-Oberklasse", "segment": "Elektro-Oberklasse-Limousine", "body_style": "Limousine", "new_price": 72000, "hp": 292, "engine_displacement": 0.0, "rarity_multiplier": 1.15, "demand_factor": 1.2},
    {"brand": "Mercedes", "model": "EQS", "generation": "V297", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-Luxus", "segment": "Elektro-Luxuslimousine", "body_style": "Limousine", "new_price": 110000, "hp": 333, "engine_displacement": 0.0, "rarity_multiplier": 1.2, "demand_factor": 1.25},
    {"brand": "Mercedes", "model": "EQS SUV", "generation": "X296", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Elektro-Luxus", "segment": "Elektro-Luxus-SUV", "body_style": "SUV", "new_price": 115000, "hp": 544, "engine_displacement": 0.0, "rarity_multiplier": 1.2, "demand_factor": 1.25},

    # ========================================
    # AUDI (25 Modelle)
    # ========================================
    {"brand": "Audi", "model": "A1", "generation": "GB", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Kleinwagen", "segment": "Premium-Kleinwagen", "body_style": "Kleinwagen", "new_price": 23000, "hp": 95, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "A3", "generation": "8Y", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Kompakt-Premium", "segment": "Premium-Kompaktklasse", "body_style": "Schrägheck", "new_price": 34000, "hp": 150, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "A4", "generation": "B9", "facelift": False, "year_start": 2016, "year_end": 2019, "category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 40000, "hp": 150, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "A4", "generation": "B9 FL", "facelift": True, "year_start": 2019, "year_end": 2023, "category": "Mittelklasse-Premium", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 42000, "hp": 150, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "A5", "generation": "F5", "facelift": False, "year_start": 2016, "year_end": 2025, "category": "Coupé-Premium", "segment": "Premium-Coupé", "body_style": "Coupé", "new_price": 48000, "hp": 190, "engine_displacement": 2.0, "rarity_multiplier": 1.05},
    {"brand": "Audi", "model": "A6", "generation": "C8", "facelift": False, "year_start": 2018, "year_end": 2024, "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 58000, "hp": 204, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "A6", "generation": "C8 FL", "facelift": True, "year_start": 2024, "year_end": 2025, "category": "Oberklasse", "segment": "Obere Mittelklasse", "body_style": "Limousine", "new_price": 62000, "hp": 204, "engine_displacement": 2.0, "rarity_multiplier": 1.0, "demand_factor": 1.05},
    {"brand": "Audi", "model": "A7", "generation": "4K", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Oberklasse", "segment": "Gran Turismo", "body_style": "Coupé", "new_price": 72000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.1},
    {"brand": "Audi", "model": "A8", "generation": "D5", "facelift": False, "year_start": 2017, "year_end": 2022, "category": "Luxuslimousine", "segment": "Luxus-Limousine", "body_style": "Limousine", "new_price": 92000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.05},
    {"brand": "Audi", "model": "A8", "generation": "D5 FL", "facelift": True, "year_start": 2022, "year_end": 2025, "category": "Luxuslimousine", "segment": "Luxus-Limousine", "body_style": "Limousine", "new_price": 95000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.05},
    {"brand": "Audi", "model": "Q2", "generation": "GA", "facelift": False, "year_start": 2016, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 28000, "hp": 116, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "Q3", "generation": "F3", "facelift": False, "year_start": 2018, "year_end": 2023, "category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_style": "SUV", "new_price": 36000, "hp": 150, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "Q3", "generation": "F3 FL", "facelift": True, "year_start": 2023, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Premium-Kompakt-SUV", "body_style": "SUV", "new_price": 38000, "hp": 150, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "Q5", "generation": "FY", "facelift": False, "year_start": 2017, "year_end": 2020, "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 48000, "hp": 190, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "Q5", "generation": "FY FL", "facelift": True, "year_start": 2020, "year_end": 2025, "category": "SUV-Mittel", "segment": "Premium-Mittelklasse-SUV", "body_style": "SUV", "new_price": 52000, "hp": 204, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "Q7", "generation": "4M", "facelift": False, "year_start": 2015, "year_end": 2019, "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 65000, "hp": 252, "engine_displacement": 3.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "Q7", "generation": "4M FL", "facelift": True, "year_start": 2019, "year_end": 2025, "category": "SUV-Premium", "segment": "Oberklasse-SUV", "body_style": "SUV", "new_price": 68000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.0},
    {"brand": "Audi", "model": "Q8", "generation": "4M", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "SUV-Premium", "segment": "SUV-Coupé", "body_style": "SUV-Coupé", "new_price": 78000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.1},
    {"brand": "Audi", "model": "RS3", "generation": "8Y", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Sportwagen", "segment": "Performance-Kompaktklasse", "body_style": "Limousine", "new_price": 62000, "hp": 400, "engine_displacement": 2.5, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.35, "demand_factor": 1.3},
    {"brand": "Audi", "model": "RS5", "generation": "F5", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "Sportwagen", "segment": "Performance-Coupé", "body_style": "Coupé", "new_price": 88000, "hp": 450, "engine_displacement": 2.9, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.4, "demand_factor": 1.35},
    {"brand": "Audi", "model": "RS6 Avant", "generation": "C8", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Supersportwagen", "segment": "Performance-Kombi", "body_style": "Kombi", "new_price": 125000, "hp": 600, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.45},
    {"brand": "Audi", "model": "RS7", "generation": "4K", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Supersportwagen", "segment": "Performance-Sportback", "body_style": "Coupé", "new_price": 135000, "hp": 600, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.45},
    {"brand": "Audi", "model": "Q4 e-tron", "generation": "E2", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 48000, "hp": 204, "engine_displacement": 0.0, "rarity_multiplier": 1.05, "demand_factor": 1.1},
    {"brand": "Audi", "model": "e-tron GT", "generation": "F8", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-Sportwagen", "segment": "Elektro-Gran-Turismo", "body_style": "Limousine", "new_price": 105000, "hp": 530, "engine_displacement": 0.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.3, "demand_factor": 1.35},
    {"brand": "Audi", "model": "e-tron", "generation": "GE", "facelift": False, "year_start": 2019, "year_end": 2024, "category": "Elektro-SUV", "segment": "Elektro-Oberklasse-SUV", "body_style": "SUV", "new_price": 82000, "hp": 408, "engine_displacement": 0.0, "rarity_multiplier": 1.15, "demand_factor": 1.2},

    # ========================================
    # PORSCHE (20 Modelle)
    # ========================================
    {"brand": "Porsche", "model": "911 Carrera", "generation": "992", "facelift": False, "year_start": 2019, "year_end": 2024, "category": "Supersportwagen", "segment": "Ikonen-Sportwagen", "body_style": "Coupé", "new_price": 130000, "hp": 385, "engine_displacement": 3.0, "special_edition": True, "rarity_multiplier": 1.4, "demand_factor": 1.4},
    {"brand": "Porsche", "model": "911 Carrera", "generation": "992 FL", "facelift": True, "year_start": 2024, "year_end": 2025, "category": "Supersportwagen", "segment": "Ikonen-Sportwagen", "body_style": "Coupé", "new_price": 138000, "hp": 394, "engine_displacement": 3.0, "special_edition": True, "rarity_multiplier": 1.45, "demand_factor": 1.5},
    {"brand": "Porsche", "model": "911 Carrera S", "generation": "992", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Supersportwagen", "segment": "Ikonen-Sportwagen", "body_style": "Coupé", "new_price": 155000, "hp": 450, "engine_displacement": 3.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.5},
    {"brand": "Porsche", "model": "911 Turbo", "generation": "992", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Supersportwagen", "segment": "Turbo-Sportwagen", "body_style": "Coupé", "new_price": 210000, "hp": 580, "engine_displacement": 3.8, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.55, "demand_factor": 1.55},
    {"brand": "Porsche", "model": "911 Turbo S", "generation": "992", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Supersportwagen", "segment": "Turbo-Sportwagen", "body_style": "Coupé", "new_price": 240000, "hp": 650, "engine_displacement": 3.8, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.6, "demand_factor": 1.6},
    {"brand": "Porsche", "model": "911 GT3", "generation": "992", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Supersportwagen", "segment": "Track-Sportwagen", "body_style": "Coupé", "new_price": 175000, "hp": 510, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.7, "demand_factor": 1.7},
    {"brand": "Porsche", "model": "718 Cayman", "generation": "982", "facelift": False, "year_start": 2016, "year_end": 2023, "category": "Sportwagen", "segment": "Mittelmotor-Sportwagen", "body_style": "Coupé", "new_price": 62000, "hp": 300, "engine_displacement": 2.0, "rarity_multiplier": 1.2, "demand_factor": 1.15},
    {"brand": "Porsche", "model": "718 Cayman GTS", "generation": "982", "facelift": False, "year_start": 2017, "year_end": 2023, "category": "Sportwagen", "segment": "Mittelmotor-Sportwagen", "body_style": "Coupé", "new_price": 82000, "hp": 400, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.35, "demand_factor": 1.3},
    {"brand": "Porsche", "model": "718 Boxster", "generation": "982", "facelift": False, "year_start": 2016, "year_end": 2023, "category": "Roadster", "segment": "Mittelmotor-Roadster", "body_style": "Roadster", "new_price": 64000, "hp": 300, "engine_displacement": 2.0, "rarity_multiplier": 1.25, "demand_factor": 1.2},
    {"brand": "Porsche", "model": "718 Boxster GTS", "generation": "982", "facelift": False, "year_start": 2017, "year_end": 2023, "category": "Roadster", "segment": "Performance-Roadster", "body_style": "Roadster", "new_price": 85000, "hp": 400, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.35, "demand_factor": 1.3},
    {"brand": "Porsche", "model": "Cayenne", "generation": "E3", "facelift": False, "year_start": 2017, "year_end": 2023, "category": "SUV-Premium", "segment": "Luxus-SUV", "body_style": "SUV", "new_price": 78000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.15, "demand_factor": 1.1},
    {"brand": "Porsche", "model": "Cayenne", "generation": "E3 FL", "facelift": True, "year_start": 2023, "year_end": 2025, "category": "SUV-Premium", "segment": "Luxus-SUV", "body_style": "SUV", "new_price": 82000, "hp": 340, "engine_displacement": 3.0, "rarity_multiplier": 1.15, "demand_factor": 1.15},
    {"brand": "Porsche", "model": "Cayenne Turbo", "generation": "E3", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "SUV-Super", "segment": "Performance-SUV", "body_style": "SUV", "new_price": 145000, "hp": 550, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.4, "demand_factor": 1.4},
    {"brand": "Porsche", "model": "Macan", "generation": "95B", "facelift": False, "year_start": 2014, "year_end": 2018, "category": "SUV-Sport", "segment": "Sport-SUV", "body_style": "SUV", "new_price": 58000, "hp": 252, "engine_displacement": 2.0, "rarity_multiplier": 1.1},
    {"brand": "Porsche", "model": "Macan", "generation": "95B FL", "facelift": True, "year_start": 2018, "year_end": 2024, "category": "SUV-Sport", "segment": "Sport-SUV", "body_style": "SUV", "new_price": 62000, "hp": 265, "engine_displacement": 2.0, "rarity_multiplier": 1.1},
    {"brand": "Porsche", "model": "Macan GTS", "generation": "95B", "facelift": False, "year_start": 2015, "year_end": 2024, "category": "SUV-Sport", "segment": "Performance-SUV", "body_style": "SUV", "new_price": 78000, "hp": 380, "engine_displacement": 2.9, "special_edition": True, "rarity_multiplier": 1.25, "demand_factor": 1.2},
    {"brand": "Porsche", "model": "Taycan", "generation": "Y1A", "facelift": False, "year_start": 2019, "year_end": 2023, "category": "Elektro-Sportwagen", "segment": "Elektro-Gran-Turismo", "body_style": "Limousine", "new_price": 92000, "hp": 408, "engine_displacement": 0.0, "rarity_multiplier": 1.25, "demand_factor": 1.25},
    {"brand": "Porsche", "model": "Taycan", "generation": "Y1A FL", "facelift": True, "year_start": 2023, "year_end": 2025, "category": "Elektro-Sportwagen", "segment": "Elektro-Gran-Turismo", "body_style": "Limousine", "new_price": 95000, "hp": 408, "engine_displacement": 0.0, "rarity_multiplier": 1.3, "demand_factor": 1.3},
    {"brand": "Porsche", "model": "Taycan Turbo S", "generation": "Y1A", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Elektro-Sportwagen", "segment": "Elektro-Gran-Turismo", "body_style": "Limousine", "new_price": 190000, "hp": 761, "engine_displacement": 0.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.5},
    {"brand": "Porsche", "model": "Panamera", "generation": "G2", "facelift": False, "year_start": 2016, "year_end": 2020, "category": "Luxuslimousine", "segment": "Gran Turismo", "body_style": "Limousine", "new_price": 95000, "hp": 330, "engine_displacement": 3.0, "rarity_multiplier": 1.15},

    # ========================================
    # TESLA (8 Modelle)
    # ========================================
    {"brand": "Tesla", "model": "Model 3", "generation": "Standard", "facelift": False, "year_start": 2017, "year_end": 2023, "category": "Elektro-Mittelklasse", "segment": "Elektro-Limousine", "body_style": "Limousine", "new_price": 40000, "hp": 283, "engine_displacement": 0.0, "rarity_multiplier": 1.05, "demand_factor": 1.1},
    {"brand": "Tesla", "model": "Model 3", "generation": "Highland", "facelift": True, "year_start": 2023, "year_end": 2025, "category": "Elektro-Mittelklasse", "segment": "Elektro-Limousine", "body_style": "Limousine", "new_price": 42000, "hp": 283, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},
    {"brand": "Tesla", "model": "Model 3 Performance", "generation": "Highland", "facelift": True, "year_start": 2023, "year_end": 2025, "category": "Elektro-Sportwagen", "segment": "Elektro-Performance", "body_style": "Limousine", "new_price": 54000, "hp": 460, "engine_displacement": 0.0, "special_edition": True, "rarity_multiplier": 1.25, "demand_factor": 1.25},
    {"brand": "Tesla", "model": "Model S", "generation": "Plaid", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-Oberklasse", "segment": "Elektro-Luxuslimousine", "body_style": "Limousine", "new_price": 110000, "hp": 1020, "engine_displacement": 0.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.4, "demand_factor": 1.4},
    {"brand": "Tesla", "model": "Model X", "generation": "Plaid", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Luxus-SUV", "body_style": "SUV", "new_price": 120000, "hp": 1020, "engine_displacement": 0.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.4, "demand_factor": 1.45},
    {"brand": "Tesla", "model": "Model Y", "generation": "Standard", "facelift": False, "year_start": 2021, "year_end": 2024, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 45000, "hp": 378, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},
    {"brand": "Tesla", "model": "Model Y", "generation": "Juniper", "facelift": True, "year_start": 2024, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 48000, "hp": 378, "engine_displacement": 0.0, "rarity_multiplier": 1.15, "demand_factor": 1.2},
    {"brand": "Tesla", "model": "Model Y Performance", "generation": "Standard", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-Sportwagen", "segment": "Elektro-Performance-SUV", "body_style": "SUV", "new_price": 58000, "hp": 534, "engine_displacement": 0.0, "special_edition": True, "rarity_multiplier": 1.25, "demand_factor": 1.3},

    # ========================================
    # PREMIUM & EXOTIC BRANDS (30 Modelle)
    # ========================================
    
    # FERRARI
    {"brand": "Ferrari", "model": "F8 Tributo", "generation": "F142", "facelift": False, "year_start": 2019, "year_end": 2023, "category": "Supersportwagen", "segment": "Supersportwagen", "body_style": "Coupé", "new_price": 280000, "hp": 720, "engine_displacement": 3.9, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.7, "demand_factor": 1.7},
    {"brand": "Ferrari", "model": "Roma", "generation": "F169", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Supersportwagen", "segment": "Gran Turismo", "body_style": "Coupé", "new_price": 235000, "hp": 620, "engine_displacement": 3.9, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.6, "demand_factor": 1.6},
    {"brand": "Ferrari", "model": "SF90 Stradale", "generation": "F173", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Hypersportwagen", "segment": "Hybrid-Supersportwagen", "body_style": "Coupé", "new_price": 500000, "hp": 1000, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 2.0, "demand_factor": 2.0},
    {"brand": "Ferrari", "model": "296 GTB", "generation": "F171", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Supersportwagen", "segment": "Hybrid-Sportwagen", "body_style": "Coupé", "new_price": 270000, "hp": 830, "engine_displacement": 3.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.75, "demand_factor": 1.75},
    {"brand": "Ferrari", "model": "Portofino", "generation": "F164", "facelift": False, "year_start": 2017, "year_end": 2023, "category": "Cabrio-Sport", "segment": "GT-Cabrio", "body_style": "Cabrio", "new_price": 210000, "hp": 620, "engine_displacement": 3.9, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.55, "demand_factor": 1.5},
    
    # LAMBORGHINI
    {"brand": "Lamborghini", "model": "Huracán", "generation": "LB724", "facelift": False, "year_start": 2014, "year_end": 2019, "category": "Supersportwagen", "segment": "Supersportwagen", "body_style": "Coupé", "new_price": 210000, "hp": 610, "engine_displacement": 5.2, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.65, "demand_factor": 1.6},
    {"brand": "Lamborghini", "model": "Huracán EVO", "generation": "LB724 FL", "facelift": True, "year_start": 2019, "year_end": 2024, "category": "Supersportwagen", "segment": "Supersportwagen", "body_style": "Coupé", "new_price": 220000, "hp": 640, "engine_displacement": 5.2, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.7, "demand_factor": 1.65},
    {"brand": "Lamborghini", "model": "Aventador", "generation": "LB834", "facelift": False, "year_start": 2011, "year_end": 2022, "category": "Supersportwagen", "segment": "V12-Supersportwagen", "body_style": "Coupé", "new_price": 420000, "hp": 740, "engine_displacement": 6.5, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.9, "demand_factor": 1.85},
    {"brand": "Lamborghini", "model": "Urus", "generation": "LB736", "facelift": False, "year_start": 2018, "year_end": 2022, "category": "SUV-Super", "segment": "Super-SUV", "body_style": "SUV", "new_price": 210000, "hp": 650, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.65, "demand_factor": 1.65},
    {"brand": "Lamborghini", "model": "Urus S", "generation": "LB736 FL", "facelift": True, "year_start": 2022, "year_end": 2025, "category": "SUV-Super", "segment": "Super-SUV", "body_style": "SUV", "new_price": 220000, "hp": 666, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.7, "demand_factor": 1.7},
    {"brand": "Lamborghini", "model": "Revuelto", "generation": "LB744", "facelift": False, "year_start": 2023, "year_end": 2025, "category": "Hypersportwagen", "segment": "V12-Hybrid", "body_style": "Coupé", "new_price": 550000, "hp": 1015, "engine_displacement": 6.5, "special_edition": True, "premium_package": True, "rarity_multiplier": 2.1, "demand_factor": 2.0},
    
    # MCLAREN
    {"brand": "McLaren", "model": "720S", "generation": "P14", "facelift": False, "year_start": 2017, "year_end": 2023, "category": "Supersportwagen", "segment": "Supersportwagen", "body_style": "Coupé", "new_price": 290000, "hp": 720, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.75, "demand_factor": 1.7},
    {"brand": "McLaren", "model": "Artura", "generation": "P18", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Supersportwagen", "segment": "Hybrid-Sportwagen", "body_style": "Coupé", "new_price": 240000, "hp": 680, "engine_displacement": 3.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.7, "demand_factor": 1.65},
    
    # BENTLEY
    {"brand": "Bentley", "model": "Continental GT", "generation": "GTC3", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Luxus-Coupé", "segment": "Gran Turismo", "body_style": "Coupé", "new_price": 220000, "hp": 635, "engine_displacement": 6.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.6, "demand_factor": 1.55},
    {"brand": "Bentley", "model": "Bentayga", "generation": "4V", "facelift": False, "year_start": 2016, "year_end": 2020, "category": "SUV-Ultraluxus", "segment": "Ultraluxus-SUV", "body_style": "SUV", "new_price": 190000, "hp": 608, "engine_displacement": 6.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.55, "demand_factor": 1.5},
    {"brand": "Bentley", "model": "Bentayga", "generation": "4V FL", "facelift": True, "year_start": 2020, "year_end": 2025, "category": "SUV-Ultraluxus", "segment": "Ultraluxus-SUV", "body_style": "SUV", "new_price": 200000, "hp": 550, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.55, "demand_factor": 1.55},
    {"brand": "Bentley", "model": "Flying Spur", "generation": "BY", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Ultraluxus", "segment": "Luxus-Limousine", "body_style": "Limousine", "new_price": 210000, "hp": 635, "engine_displacement": 6.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.6, "demand_factor": 1.55},
    
    # ROLLS-ROYCE
    {"brand": "Rolls-Royce", "model": "Ghost", "generation": "II", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Ultraluxus", "segment": "Ultraluxus-Limousine", "body_style": "Limousine", "new_price": 320000, "hp": 571, "engine_displacement": 6.75, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.8, "demand_factor": 1.75},
    {"brand": "Rolls-Royce", "model": "Cullinan", "generation": "RR31", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "SUV-Ultraluxus", "segment": "Ultraluxus-SUV", "body_style": "SUV", "new_price": 340000, "hp": 571, "engine_displacement": 6.75, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.85, "demand_factor": 1.8},
    
    # ASTON MARTIN
    {"brand": "Aston Martin", "model": "Vantage", "generation": "AG3", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Sportwagen", "segment": "GT-Sportwagen", "body_style": "Coupé", "new_price": 180000, "hp": 510, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.45},
    {"brand": "Aston Martin", "model": "DB11", "generation": "AG1", "facelift": False, "year_start": 2016, "year_end": 2023, "category": "Luxus-Coupé", "segment": "Gran Turismo", "body_style": "Coupé", "new_price": 220000, "hp": 630, "engine_displacement": 5.2, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.6, "demand_factor": 1.55},
    {"brand": "Aston Martin", "model": "DBX", "generation": "AG4", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "SUV-Luxus", "segment": "Luxus-SUV", "body_style": "SUV", "new_price": 210000, "hp": 550, "engine_displacement": 4.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.55, "demand_factor": 1.5},
    
    # MASERATI
    {"brand": "Maserati", "model": "Ghibli", "generation": "M157", "facelift": False, "year_start": 2013, "year_end": 2023, "category": "Oberklasse", "segment": "Italienische Limousine", "body_style": "Limousine", "new_price": 82000, "hp": 350, "engine_displacement": 3.0, "rarity_multiplier": 1.15, "demand_factor": 1.1},
    {"brand": "Maserati", "model": "Quattroporte", "generation": "M156", "facelift": False, "year_start": 2013, "year_end": 2025, "category": "Luxuslimousine", "segment": "Luxus-Limousine", "body_style": "Limousine", "new_price": 130000, "hp": 580, "engine_displacement": 3.8, "special_edition": True, "rarity_multiplier": 1.3, "demand_factor": 1.25},
    {"brand": "Maserati", "model": "Levante", "generation": "M161", "facelift": False, "year_start": 2016, "year_end": 2025, "category": "SUV-Premium", "segment": "Luxus-SUV", "body_style": "SUV", "new_price": 88000, "hp": 350, "engine_displacement": 3.0, "rarity_multiplier": 1.2, "demand_factor": 1.15},
    {"brand": "Maserati", "model": "MC20", "generation": "M240", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Supersportwagen", "segment": "Mittelmotor-Sportwagen", "body_style": "Coupé", "new_price": 230000, "hp": 630, "engine_displacement": 3.0, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.65, "demand_factor": 1.6},
    {"brand": "Maserati", "model": "Grecale", "generation": "M183", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "SUV-Mittel", "segment": "Premium-SUV", "body_style": "SUV", "new_price": 72000, "hp": 330, "engine_displacement": 2.0, "rarity_multiplier": 1.15, "demand_factor": 1.15},

    # ========================================
    # MASS MARKET BRANDS (50 Modelle)
    # ========================================
    
    # TOYOTA
    {"brand": "Toyota", "model": "Yaris", "generation": "XP21", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Kleinwagen", "segment": "Kleinwagen", "body_style": "Kleinwagen", "new_price": 20000, "hp": 120, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Toyota", "model": "Corolla", "generation": "E210", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Limousine", "new_price": 28000, "hp": 125, "engine_displacement": 1.8, "rarity_multiplier": 1.0},
    {"brand": "Toyota", "model": "Camry", "generation": "XV70", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "Mittelklasse", "segment": "Mittelklasse", "body_style": "Limousine", "new_price": 38000, "hp": 218, "engine_displacement": 2.5, "rarity_multiplier": 1.0},
    {"brand": "Toyota", "model": "RAV4", "generation": "XA50", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 32000, "hp": 222, "engine_displacement": 2.5, "rarity_multiplier": 1.0},
    {"brand": "Toyota", "model": "Highlander", "generation": "XU70", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Mittel", "segment": "Mittelklasse-SUV-7-Sitzer", "body_style": "SUV", "new_price": 48000, "hp": 265, "engine_displacement": 3.5, "rarity_multiplier": 1.05},
    {"brand": "Toyota", "model": "Supra", "generation": "J29", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Sportwagen", "segment": "Sportwagen", "body_style": "Coupé", "new_price": 58000, "hp": 340, "engine_displacement": 3.0, "special_edition": True, "rarity_multiplier": 1.3, "demand_factor": 1.25},
    {"brand": "Toyota", "model": "GR86", "generation": "ZN8", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Sportwagen", "segment": "Sport-Coupé", "body_style": "Coupé", "new_price": 32000, "hp": 234, "engine_displacement": 2.4, "rarity_multiplier": 1.15, "demand_factor": 1.15},
    
    # HONDA
    {"brand": "Honda", "model": "Jazz", "generation": "GK", "facelift": False, "year_start": 2015, "year_end": 2020, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 18000, "hp": 102, "engine_displacement": 1.3, "rarity_multiplier": 1.0},
    {"brand": "Honda", "model": "Civic", "generation": "FC", "facelift": False, "year_start": 2017, "year_end": 2021, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Limousine", "new_price": 26000, "hp": 182, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Honda", "model": "Civic", "generation": "FL", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Limousine", "new_price": 32000, "hp": 180, "engine_displacement": 1.5, "rarity_multiplier": 1.0, "demand_factor": 1.05},
    {"brand": "Honda", "model": "Civic Type R", "generation": "FK8", "facelift": False, "year_start": 2017, "year_end": 2021, "category": "Sport", "segment": "Hot Hatch", "body_style": "Schrägheck", "new_price": 45000, "hp": 320, "engine_displacement": 2.0, "special_edition": True, "rarity_multiplier": 1.3, "demand_factor": 1.3},
    {"brand": "Honda", "model": "Civic Type R", "generation": "FL5", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Sport", "segment": "Hot Hatch", "body_style": "Schrägheck", "new_price": 52000, "hp": 330, "engine_displacement": 2.0, "special_edition": True, "rarity_multiplier": 1.35, "demand_factor": 1.35},
    {"brand": "Honda", "model": "CR-V", "generation": "RW", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 32000, "hp": 193, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Honda", "model": "e", "generation": "ZC7", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Elektro-Kompakt", "segment": "Elektro-City-Car", "body_style": "Kleinwagen", "new_price": 38000, "hp": 154, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.1},
    
    # MAZDA
    {"brand": "Mazda", "model": "2", "generation": "DJ", "facelift": False, "year_start": 2014, "year_end": 2025, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 18000, "hp": 90, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Mazda", "model": "3", "generation": "BP", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Limousine", "new_price": 26000, "hp": 122, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Mazda", "model": "CX-30", "generation": "DM", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Crossover", "body_style": "SUV", "new_price": 28000, "hp": 122, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Mazda", "model": "CX-5", "generation": "KF", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 32000, "hp": 165, "engine_displacement": 2.0, "rarity_multiplier": 1.0},
    {"brand": "Mazda", "model": "MX-5", "generation": "ND", "facelift": False, "year_start": 2015, "year_end": 2018, "category": "Roadster", "segment": "Roadster", "body_style": "Roadster", "new_price": 28000, "hp": 131, "engine_displacement": 1.5, "rarity_multiplier": 1.1, "demand_factor": 1.1},
    {"brand": "Mazda", "model": "MX-5", "generation": "ND2", "facelift": True, "year_start": 2018, "year_end": 2025, "category": "Roadster", "segment": "Roadster", "body_style": "Roadster", "new_price": 32000, "hp": 184, "engine_displacement": 2.0, "rarity_multiplier": 1.15, "demand_factor": 1.15},
    
    # NISSAN
    {"brand": "Nissan", "model": "Micra", "generation": "K14", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 16000, "hp": 90, "engine_displacement": 0.9, "rarity_multiplier": 1.0},
    {"brand": "Nissan", "model": "Juke", "generation": "F16", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Klein", "segment": "Mini-SUV", "body_style": "SUV", "new_price": 24000, "hp": 117, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Nissan", "model": "Qashqai", "generation": "J12", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 30000, "hp": 158, "engine_displacement": 1.3, "rarity_multiplier": 1.0},
    {"brand": "Nissan", "model": "X-Trail", "generation": "T33", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "SUV-Mittel", "segment": "Mittelklasse-SUV", "body_style": "SUV", "new_price": 38000, "hp": 163, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Nissan", "model": "Leaf", "generation": "ZE1", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "Elektro-Kompakt", "segment": "Elektro-Kompaktklasse", "body_style": "Schrägheck", "new_price": 35000, "hp": 217, "engine_displacement": 0.0, "rarity_multiplier": 1.05},
    {"brand": "Nissan", "model": "Ariya", "generation": "FE0", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 48000, "hp": 242, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.1},
    {"brand": "Nissan", "model": "GT-R", "generation": "R35", "facelift": False, "year_start": 2007, "year_end": 2025, "category": "Supersportwagen", "segment": "Supersportwagen", "body_style": "Coupé", "new_price": 130000, "hp": 570, "engine_displacement": 3.8, "special_edition": True, "premium_package": True, "rarity_multiplier": 1.5, "demand_factor": 1.5},
    
    # HYUNDAI
    {"brand": "Hyundai", "model": "i10", "generation": "BC3", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kleinstwagen", "segment": "City-Car", "body_style": "Kleinwagen", "new_price": 14000, "hp": 67, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Hyundai", "model": "i20", "generation": "BC3", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 18000, "hp": 100, "engine_displacement": 1.2, "rarity_multiplier": 1.0},
    {"brand": "Hyundai", "model": "i30", "generation": "PD", "facelift": False, "year_start": 2017, "year_end": 2024, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 22000, "hp": 120, "engine_displacement": 1.4, "rarity_multiplier": 1.0},
    {"brand": "Hyundai", "model": "i30 N", "generation": "PD", "facelift": False, "year_start": 2017, "year_end": 2024, "category": "Sport", "segment": "Hot Hatch", "body_style": "Schrägheck", "new_price": 38000, "hp": 280, "engine_displacement": 2.0, "special_edition": True, "rarity_multiplier": 1.25, "demand_factor": 1.2},
    {"brand": "Hyundai", "model": "Tucson", "generation": "NX4", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 32000, "hp": 180, "engine_displacement": 1.6, "rarity_multiplier": 1.0},
    {"brand": "Hyundai", "model": "Santa Fe", "generation": "TM", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "SUV-Mittel", "segment": "Mittelklasse-SUV-7-Sitzer", "body_style": "SUV", "new_price": 45000, "hp": 200, "engine_displacement": 2.2, "rarity_multiplier": 1.0},
    {"brand": "Hyundai", "model": "Kona Electric", "generation": "OS", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Kompakt-SUV", "body_style": "SUV", "new_price": 38000, "hp": 204, "engine_displacement": 0.0, "rarity_multiplier": 1.05, "demand_factor": 1.1},
    {"brand": "Hyundai", "model": "Ioniq 5", "generation": "NE", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Crossover", "body_style": "SUV", "new_price": 48000, "hp": 325, "engine_displacement": 0.0, "rarity_multiplier": 1.15, "demand_factor": 1.2},
    
    # KIA
    {"brand": "Kia", "model": "Picanto", "generation": "JA", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "Kleinstwagen", "segment": "City-Car", "body_style": "Kleinwagen", "new_price": 13000, "hp": 67, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Kia", "model": "Rio", "generation": "YB", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 17000, "hp": 100, "engine_displacement": 1.25, "rarity_multiplier": 1.0},
    {"brand": "Kia", "model": "Ceed", "generation": "CD", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 22000, "hp": 140, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Kia", "model": "Stonic", "generation": "YB", "facelift": False, "year_start": 2017, "year_end": 2025, "category": "SUV-Klein", "segment": "Mini-SUV", "body_style": "SUV", "new_price": 20000, "hp": 100, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Kia", "model": "Sportage", "generation": "NQ5", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 32000, "hp": 180, "engine_displacement": 1.6, "rarity_multiplier": 1.0},
    {"brand": "Kia", "model": "Sorento", "generation": "MQ4", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "SUV-Mittel", "segment": "Mittelklasse-SUV-7-Sitzer", "body_style": "SUV", "new_price": 45000, "hp": 265, "engine_displacement": 2.2, "rarity_multiplier": 1.0},
    {"brand": "Kia", "model": "EV6", "generation": "CV", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Crossover", "body_style": "SUV", "new_price": 48000, "hp": 229, "engine_displacement": 0.0, "rarity_multiplier": 1.15, "demand_factor": 1.2},
    {"brand": "Kia", "model": "EV6 GT", "generation": "CV", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Elektro-Sportwagen", "segment": "Elektro-Performance-Crossover", "body_style": "SUV", "new_price": 68000, "hp": 585, "engine_displacement": 0.0, "special_edition": True, "rarity_multiplier": 1.35, "demand_factor": 1.35},

    # ========================================
    # WEITERE MARKEN (20 Modelle)
    # ========================================
    
    # OPEL
    {"brand": "Opel", "model": "Corsa", "generation": "F", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kleinwagen", "segment": "Kleinwagen", "body_style": "Kleinwagen", "new_price": 18000, "hp": 100, "engine_displacement": 1.2, "rarity_multiplier": 1.0},
    {"brand": "Opel", "model": "Astra", "generation": "L", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 25000, "hp": 130, "engine_displacement": 1.2, "rarity_multiplier": 1.0},
    {"brand": "Opel", "model": "Mokka", "generation": "B", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "SUV-Klein", "segment": "Mini-SUV", "body_style": "SUV", "new_price": 24000, "hp": 130, "engine_displacement": 1.2, "rarity_multiplier": 1.0},
    
    # FORD
    {"brand": "Ford", "model": "Fiesta", "generation": "VIII", "facelift": False, "year_start": 2017, "year_end": 2023, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 17000, "hp": 100, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Ford", "model": "Focus", "generation": "IV", "facelift": False, "year_start": 2018, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 24000, "hp": 125, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Ford", "model": "Puma", "generation": "I", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Klein", "segment": "Mini-SUV", "body_style": "SUV", "new_price": 26000, "hp": 125, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Ford", "model": "Kuga", "generation": "III", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 32000, "hp": 150, "engine_displacement": 1.5, "rarity_multiplier": 1.0},
    {"brand": "Ford", "model": "Mustang", "generation": "S550", "facelift": False, "year_start": 2015, "year_end": 2023, "category": "Sportwagen", "segment": "Muscle Car", "body_style": "Coupé", "new_price": 48000, "hp": 450, "engine_displacement": 5.0, "special_edition": True, "rarity_multiplier": 1.25, "demand_factor": 1.2},
    {"brand": "Ford", "model": "Mustang GT", "generation": "S650", "facelift": False, "year_start": 2023, "year_end": 2025, "category": "Sportwagen", "segment": "Muscle Car", "body_style": "Coupé", "new_price": 55000, "hp": 486, "engine_displacement": 5.0, "special_edition": True, "rarity_multiplier": 1.3, "demand_factor": 1.25},
    {"brand": "Ford", "model": "Mustang Mach-E", "generation": "CE1", "facelift": False, "year_start": 2020, "year_end": 2025, "category": "Elektro-SUV", "segment": "Elektro-Performance-SUV", "body_style": "SUV", "new_price": 52000, "hp": 351, "engine_displacement": 0.0, "rarity_multiplier": 1.15, "demand_factor": 1.2},
    
    # PEUGEOT
    {"brand": "Peugeot", "model": "208", "generation": "P21", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 20000, "hp": 100, "engine_displacement": 1.2, "rarity_multiplier": 1.0},
    {"brand": "Peugeot", "model": "308", "generation": "P51", "facelift": False, "year_start": 2021, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 28000, "hp": 130, "engine_displacement": 1.2, "rarity_multiplier": 1.0},
    {"brand": "Peugeot", "model": "2008", "generation": "P24", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Klein", "segment": "Mini-SUV", "body_style": "SUV", "new_price": 25000, "hp": 130, "engine_displacement": 1.2, "rarity_multiplier": 1.0},
    {"brand": "Peugeot", "model": "3008", "generation": "P84", "facelift": False, "year_start": 2016, "year_end": 2025, "category": "SUV-Kompakt", "segment": "Kompakt-SUV", "body_style": "SUV", "new_price": 32000, "hp": 130, "engine_displacement": 1.2, "rarity_multiplier": 1.0},
    
    # RENAULT
    {"brand": "Renault", "model": "Clio", "generation": "V", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "Kleinwagen", "segment": "Supermini", "body_style": "Kleinwagen", "new_price": 19000, "hp": 100, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Renault", "model": "Megane", "generation": "IV", "facelift": False, "year_start": 2016, "year_end": 2025, "category": "Kompakt", "segment": "Kompaktklasse", "body_style": "Schrägheck", "new_price": 24000, "hp": 140, "engine_displacement": 1.3, "rarity_multiplier": 1.0},
    {"brand": "Renault", "model": "Captur", "generation": "II", "facelift": False, "year_start": 2019, "year_end": 2025, "category": "SUV-Klein", "segment": "Mini-SUV", "body_style": "SUV", "new_price": 23000, "hp": 100, "engine_displacement": 1.0, "rarity_multiplier": 1.0},
    {"brand": "Renault", "model": "Megane E-Tech", "generation": "V", "facelift": False, "year_start": 2022, "year_end": 2025, "category": "Elektro-Kompakt", "segment": "Elektro-Crossover", "body_style": "SUV", "new_price": 42000, "hp": 220, "engine_displacement": 0.0, "rarity_multiplier": 1.1, "demand_factor": 1.15},
    
    # MINI
    {"brand": "Mini", "model": "Cooper", "generation": "F56", "facelift": False, "year_start": 2014, "year_end": 2021, "category": "Kleinwagen", "segment": "Premium-Kleinwagen", "body_style": "Kleinwagen", "new_price": 24000, "hp": 136, "engine_displacement": 1.5, "rarity_multiplier": 1.05},
    {"brand": "Mini", "model": "Cooper S", "generation": "F56 FL", "facelift": True, "year_start": 2021, "year_end": 2025, "category": "Kleinwagen", "segment": "Premium-Kleinwagen", "body_style": "Kleinwagen", "new_price": 28000, "hp": 178, "engine_displacement": 2.0, "rarity_multiplier": 1.1, "demand_factor": 1.1},
]

# ANGEPASSTE BASE HOURLY RATES (realistisch für Carsharing)
BASE_HOURLY_RATES = {
    "Kleinstwagen": 8.0,
    "Kleinwagen": 10.0,
    "Kompakt": 14.0,
    "Kompakt-Premium": 18.0,
    "Mittelklasse": 20.0,
    "Mittelklasse-Premium": 25.0,
    "Oberklasse": 35.0,
    "Luxuslimousine": 60.0,
    "Ultraluxus": 120.0,
    "Hypersportwagen": 250.0,
    "Coupé-Premium": 28.0,
    "Luxus-Coupé": 50.0,
    "Cabrio-Klein": 15.0,
    "Cabrio-Premium": 32.0,
    "Cabrio-Sport": 45.0,
    "Luxus-Cabrio": 65.0,
    "Roadster": 35.0,
    "Luxus-Roadster": 75.0,
    "SUV-Klein": 15.0,
    "SUV-Kompakt": 18.0,
    "SUV-Mittel": 25.0,
    "SUV-Sport": 38.0,
    "SUV-Premium": 42.0,
    "SUV-Luxus": 65.0,
    "SUV-Ultraluxus": 110.0,
    "SUV-Super": 90.0,
    "SUV-Offroad": 45.0,
    "SUV-Coupé": 35.0,
    "SUV-Cabrio": 38.0,
    "Sport": 40.0,
    "Sportwagen": 65.0,
    "Luxus-Sportwagen": 95.0,
    "Supersportwagen": 150.0,
    "Transporter": 18.0,
    "Hochdachkombi": 15.0,
    "Kompakt-Van": 16.0,
    "Elektro-Kompakt": 16.0,
    "Elektro-Mittelklasse": 22.0,
    "Elektro-Premium": 30.0,
    "Elektro-Oberklasse": 45.0,
    "Elektro-Luxus": 65.0,
    "Elektro-SUV": 35.0,
    "Elektro-Sportwagen": 75.0,
}
